name: Update Leaderboard

on:
  push:
    branches:
      - main

jobs:
  update_leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run updateLeaderboard.js
        run: node updateLeaderboard.js

      - name: Commit and push updated leaderboard
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add leaderboard.json
          git commit -m "Update leaderboard"
          git push
